### ISSUE TITLE
Log referrers (paths between visits)

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#10]
Unfortunately, the WebExtension API makes this sub-obvious when links are opened in new windows/tabs. The `webNavigation.onCommitted` event tells *whether* the user navigated by clicking a link, but not *whence*. The `history` API does provide this information, so we may resort to trying to look up each visit there by querying for its URL and/or visit time. Or we could try to log link clicks and wait for the corresponding tab to open. Other solutions..?

**Comment by reficul31** [comment]
Please correct me if I am wrong. How about having a session id associated with every session of the user? Every link opened by the user will contain the session id and can help map the whole session using that session id. For example if we want to find the pages opened when then user was online Tuesday between 2:30 to 3:30. We can query the database and find all the pages with the same session id essentially making a link between the pages. 
This could also help in making the mind map that was on the ideas list.

**Comment by Treora** [comment]
Giving each browser session an id is something we may do also, mainly
for technical reasons as a session does not have much conceptual meaning
(people may restore tabs and continue with a previous session, and vice
versa one can do very unrelated tasks a single browser session).

This issue is really about tracing the steps from page to page, i.e.
tracing link clicks. Much more knowledge and assocations could be
inferred from browsing behaviour, but that's for another time.

**Comment by reficul31** [comment]
Sorry for misunderstanding the question. How about we add a listener on each <a> element of the page.
Eg
```
[].forEach.call(document.querySelectorAll('a'),
    function(link){
        if(link.attributes.target) {
            link.attributes.target.value = '_self';
        }
    });
//code to link the page and the new page
```

Could this possibly work for linking the pages? I would like to make an initial implementation of this if this idea is approved and as soon as my current PR is closed.

**Comment by Treora** [comment]
I hope such listeners are not required. Following up on the initial issue description, I see two ways to get the information from the browser itself:
- Combine info from two events. Perhaps it works to listen to [webNavigation.onBeforeNavigate](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/onBeforeNavigate) and check the current tab's current URL, and then listen to [webNavigation.onCommitted](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/onCommitted) to see if `transitionType==='link'`.
- Ask the history to read the `referringVisitId` from the [visitItem](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/History/VisitItem) that was created for the currently viewed page.

Both are workarounds, around the silly browser API.

**Comment by Treora** [comment]
Planning to tackle this when making a more general tab state keeping system (#91).

**Comment by Treora** [comment]
Closing this issue; features like this one have been fading off the roadmap for a while. Maybe some day..
