### ISSUE TITLE
Clean up file/folder organisation

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#112]
The organisation of this repo has become a bit messy over time. I intend to move some things around soon, currently thinking about these changes:

- [ ] Make clearer which code is an 'extension page' (`overview`, ~~`options`~~, `page-viewer`), what is background or content script, and what is commonly usable by any of them. Be more consistent in using (or possibly remove) the separation of `background` and `content_script` folders, it is a bit confusing now.
- [x] (124319d) Move html files out of `extension`, into `src`. Rename bundled scripts (e.g. `src/overview/main.jsx`) so they match the names used in html script tags (also hard-wire output naming in gulp task). `extension` is to be more like a '`build`' output folder. (where do we put images?)
- [x] In `src/overview`, separate 'application' (`main.jsx` + `store.js`) and 'redux module' (the rest). Maybe make 'application' part reusable for e.g. options page.
- [x] Move stuff from `src/search/find-pages` into `src/page-storage`, it's not really search-related.
- [x] Consider altogether regrouping `activity-logger`, `page-analysis`, `page-storage`, and `search`, or at least define their roles and interfaces better.
- [x] Refactor `generateVisitDocId` functions etc in some sensible way.
- [x] (c73fb7e) Remove unused code: `src/browser-history`, ...more?
- [x] (354b7dc) Move `src/freeze-dry` into its own repo (or else into `util`).

**Comment by poltak** [comment]
> (where do we put images?)

Could put them in sub dirs of the main module's dir, like `src/overview/img`, reflecting the build `extension/overview/img` and just add entries for them into `staticFiles` in the gulpfile. Or have another top level dir for static assets mirroring the `src/` and `extension/` structures, like `assets/{overview,options}/{fonts,img}/`.

HTML files could be treated as static files in the same way, or could unify them in a shared template and spit them out for their respective build tasks using something like [`gulp-template`](https://www.npmjs.com/package/gulp-template).

**Comment by Treora** [comment]
Thanks still for the input. For now the question about images is solved, since there are no images anymore (using semantic-ui's icons and ditched the background). The question will probably pop up again though.

I started cleaning up in the 'cleanup' branch, checking at least some of the boxes.

**Comment by Treora** [comment]
> Move html files out of extension, into src

This one has been done in 124319d. The other tasks may have to wait a bit; upcoming feature developments may give a better picture of the logical grouping. I suspect the aspects of logging visits and storing pages should be more clearly separated.

**Comment by Treora** [comment]
Lots of reorganisation done in #135. It could always be better, but it seems good enough to close this.
