### ISSUE TITLE
Listen to / sync with browser bookmarks

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#12]
We want some easy way to explicitly mark an item as important. Perhaps solvable just by listening to the normal browser add/delete bookmark events.

We could try keep the 'memory bookmarks' in sync with the browser bookmarks (and mirror their folder structure with groups/tags/links?). Questions arise when syncing memory (but not browser bookmarks) between multiple browsers, or when importing from (/ syncing with) other bookmarking services, etcetera.

**Comment by blackforestboi** [comment]
Another idea is to just listen to the `onCreated` event of the bookmarks-API: https://developer.chrome.com/extensions/bookmarks#event-onCreated

If we cannot listen to it, maybe just periodically check of new bookmarks were added by querying the bookmarks API.

**Comment by Treora** [comment]
> Another idea is to just listen to the onCreated event of the bookmarks-API: https://developer.chrome.com/extensions/bookmarks#event-onCreated

Exactly what I meant with listening to normal browser bookmark events.

I recommend using the [MDN docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/onCreated) by the way rather Chrome's, as it is adapted for cross-browser development.

**Comment by Treora** [comment]
Let's first figure out how we want approach bookmarking at all, and then consider ways of intergation with browser's bookmarks.
