### ISSUE TITLE
GetBrowserInfo() is throwing error in chrome 

### ISSUE THREAD

**Issue by swissums** [WebMemex/webmemex-extension#122]
In omnibar.js 

The
 
```javascript 
let browserName
;(async () => {
    const browserInfo = await browser.runtime.getBrowserInfo()
    browserName = browserInfo.name
})()
```

Throws an Error in chrome as the function  `browser.runtime.getBrowserInfo()` isn't supported. [see this link](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/getBrowserInfo)

I don't fully understand why the name is needed?

**Comment by swissums** [comment]
Sorry this is in the wrong depository... meant to be in the Brainworld WebMememex

**Comment by Treora** [comment]
This has been fixed since. If this is still a problem in WorldBrain they could cherry-pick commit cf47449 from here.

Feel free to open up issues here if they are not WorldBrain-specific, most WorldBrain code is still the same.

**Comment by Treora** [comment]
> I don't fully understand why the name is needed?

If you still have that question: Firefox does not support markup (`<dim>`, `<url>`) that Chrome supports and will just display these tags literally.
