### ISSUE TITLE
Watch script not working on Windows

### ISSUE THREAD

**Issue by ali-kamalizade** [WebMemex/webmemex-extension#125]
While working on a fork of this great web extension, I noticed this when I tried to develop on Windows.

`"watch": "rm -rf ./extension && gulp watch"` (package.json) will not work on Windows systems.

You could add a Windows-specific watch script like `"win-watch": "rd /s /q extension && gulp watch" `(I don't know if this is the best solution but it seems to work).

This is found in version 0.2.4.

**Comment by Treora** [comment]
Thanks for reporting! Besides that, does everything work on Windows?

I am reluctant to add Windows-specific lines, as any changes would have to be made twice, and I could not test them. Even if this is only about `rm` now, other inconsistencies will likely appear.

I would be more open to use cross-platform commands, but I'm not sure how to go about, and the main problem would still be that I could not test and maintain it to ensure it works on Windows. If enough others could, and would also need it, it might be worth the hassle, but I expect that few interested people develop on Windows; at least not without running some posix environment (e.g. [Cygwin](https://cygwin.com)) on top.

If you end up needing and inventing other fixes in the setup, please feel free to also post them in this issue and perhaps they will help others. However, committing to support Windows does currently not seem worth the maintenance hassle; there are too many things that still have to be done on this project!

**Comment by ali-kamalizade** [comment]
No problem. Otherwise, everything seems to work so far :)
I feel you, Windows can be a challenge sometimes compared to MacOS.
Sure, I report when stumble across other Windows errors.

Update: the build commands won't work either. I'm not a console expert but, at least in development mode, you can just run gulp build.
