### ISSUE TITLE
Most links on YouTube.com broken

### ISSUE THREAD

**Issue by matzhu** [WebMemex/webmemex-extension#127]
With WebMemex enabled it seems that most links at the YouTube site (not sure about external links pointing in) are non-functional. I say most as this includes all video links. Some ad links work and navigation will expand but then those links within the nav do not work.

I tested this with all other extensions disabled.

**Comment by Treora** [comment]
Could you tell which browser you are using? And what you mean with "WebMemex enabled"? Are you just browsing with the extension installed, or does the problem occur only after storing a page?

Firefox <57 has a bug that breaks connectivity of pages (e.g. youtube videos) after snapshotting a page with webmemex (reported [here](https://github.com/WebMemex/webmemex-extension/issues/120)), but this should probably not break links, so I guess you have another problem.

**Comment by matzhu** [comment]
This is on Chrome v 61.0.3163. By "enabled" I mean the extension is installed and not disabled. But to answer your question about how I'm running it, I had "Store every visited page" turned on. 

This may be the same as Issue 120. I just read it and can confirm that turning off "Store every visited page" resolves the issue.

By breaking links I mean nothing happens when a link is clicked. I don't mean to suggest that links are being altered. I think we're talking about the same thing.

**Comment by Treora** [comment]
Storing every visited page is no longer a feature, so this bug should no longer be a problem either.
