### ISSUE TITLE
Implement numerous features

### ISSUE THREAD

**Issue by bnvk** [WebMemex/webmemex-extension#128]
I was recently looking at [WorldBrain](https://worldbrain.io)'s **memex** browser extension release (of which the core functionality is based on WebMemex's code). I think the name similarity, [which was discussed](https://github.com/WorldBrain/Memex/issues/65), will unfortunately lead to some confusion in potential new users of each project.

That said, many of the things WorldBrain implemented are great and some of the first things I feel are missing from the current **WebMemex** release. This is a bit of a catch-all for ideas and new features to implemented in coming months as well as to help focus contributions by people like me :smile:

- Tagging of snapshots
- Search by #hashtag
- More intuitive "search" field with date range
- Favoriting of snapshots
- Extension pane stays open upon clicking, but does not automatically snapshot
- Importing bookmarks & history #17
- Exporting archive #99

**Comment by Treora** [comment]
Namewise, I think it would be great if the word memex became a general term for the kind of tool we are building; especially if that popularises the concept of personal annotated knowledge libraries altogether.

Most features you mention are on my wishlist too, thanks for listing them. Besides the obious constraint of limited time to work on them, and the easily overlooked but important challenge of keeping code maintainable, an important question in my mind is the following: how do we not only design these features for this particular application/interface, but also adopt or create a model for making them interoperate with other software? For example, I don't want to end up with favourites or tags on my snapshots that can only be understood and searched by this same extension. So I am tempted to start at the problem of exporting an archive (#99), or more accurately, creating and manipulating data outside our little silo. Other features that require data model can then be defined on top of that.

Purely UX-related features, such as keeping the popup open or tweaking the search feature, are of course of a different sort, and open for improvement anytime!

**Comment by blackforestboi** [comment]
hey @bnvk! great to see you surfacing after the new year. :)

> Namewise, I think it would be great if the word memex became a general term for the kind of tool we are building; especially if that popularises the concept of personal annotated knowledge libraries altogether.

Yeah I have been thinking the same here. Memex is already such a common concept, that by calling them all Memex, it feels to me that we leave the mental door open for the software being adapted in various ways all with the goal of helping people to organise their knowledge better. 

As for the features mentioned:
We have integrated some of them and the code used for it might help. 
- Tagging of snapshots **done (in our case pages)**
- Search by #hashtag **done**
- More intuitive "search" field with date range **done**
- Favoriting of snapshots **done (in our case pages)**
- Importing bookmarks & history **done**
- Exporting archive *(in progress with: https://github.com/WorldBrain/Memex/pull/224)*

In case you have problems finding the respective code, don't hesitate to ping, we're glad to help. 

Btw. @Treora, we are currently working on a new indexing library with @bluesun, @poltak & @ShishKabab in https://github.com/bluesun/fastindex
Might be of interest to you as well to integrate search capabilities into WebMemex.

**Comment by Treora** [comment]
Closing this issue. As said, some features would require a more holistic/ecosystem design, and are not likely to get (my) attention soon. I'd like to first get core things working; do less features more soundly. And features that do get attention are probably best discussed in their respective threads.
