### ISSUE TITLE
Add local files

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#13]
As a user, I want to add a local files to my web. It may suffice if I could drop files onto the overview to 'upload' them.

Ideally the system could interact more closely with the local filesystem, but this is probably outside the current project scope (while being merely a WebExtension).

**Comment by BigBlueHat** [comment]
@Treora you can setup a `file:///` access permission and then folks can just visit the file (drag it onto an empty tab) to visit it...assuming the browser can view it. Would that do what you have in mind?

**Comment by BigBlueHat** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns#scheme

**Comment by Treora** [comment]
> @Treora <https://github.com/Treora> you can setup a |file:///| access
> permission and then folks can just visit the file (drag it onto an
> empty tab) to visit it...assuming the browser can view it. Would that
> do what you have in mind?
>
I have been wondering whether using the file: scheme is a viable option.
I have the impression that it has got little love from browser builders,
and I would not be surprised if we would discover some thorny issues
with it. And at least user experience would be hard to get right. For
example, a jpg image usually opens in the browser itself, while dragging
a spreadsheet onto a tab would trigger a 'download'. If we just want a
reference to the local file (assuming it will not move!), it could
perhaps still work with small workarounds, but another desire is to get
the file contents, in order to publish your web.

While playing around a bit right now, I discovered that in Chromium an
extension can actually do XHRs to get any local file, and even (an html
representation of) directory listings. Not too bad, that opens some
possibilities. No luck with XHR in Firefox though.

Still, it seems much easier to start with just providing a file
'upload', so it works the same for every type of file, nicer UX can be
created, and the contents are immediately available. I'd be glad to hear
if you have a different view, or have particular use cases in mind that
would be worthwhile to pursue.

**Comment by BigBlueHat** [comment]
There is an exploratory [File and Directory Entries API](https://wicg.github.io/entries-api/) with some level of support in Firefox and inside the `webkit` namespace: https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API

Not sure, though, how that works with extensions...or if it does at all.

Your upload plan is still probably the best. Especially when replication and such are taken into consideration.

The filesystem should be deprecated in favor of the Web. 😸

**Comment by Treora** [comment]
Not expecting to prioritise this anytime soon, cleaning it from the list for now.
