### ISSUE TITLE
Various design improvements

### ISSUE THREAD

**Issue by bnvk** [WebMemex/webmemex-extension#130]
This is a catch all for various suggested design improvements. I will send individual specific things as detailed pull-requests and tag this issue. At some point, it would be worth doing a full design refresh, but for now this should do.

**Comment by Treora** [comment]
Did you not open #128 for the same purpose?

Do you have specific plans regarding things you intend to improve? I'd be happy to brainstorm about the design together, might also save us effort from doing things twice.

**Comment by bnvk** [comment]
The other issue is more for larger features, where as this is just visual design polishing of the extension and branding. To me, new features require actual engineering + new code, where as this is just tweaking CSS, text, icons, and such.

**Comment by Treora** [comment]
Closing this issue; specific design ideas would probably best be treated in their own follow-up issues.
