### ISSUE TITLE
Consider opportunistic integrations / compatibilities

### ISSUE THREAD

**Issue by bnvk** [WebMemex/webmemex-extension#132]
As per the feature of "exporting" data from Webmemex like #99 combined with @Treora stated goal of:

> it would be great if the word memex became a general term ... especially if that popularises the concept of personal annotated knowledge libraries altogether

Seems fortuitous to keep track of some projects that it would be cool to integrate with on some level. In short, after moving to 100% FOSS OS and apps, the main thing I miss is a suitable replacement for Evernote, and specifically there "page snapshot" feature that then saves your data and syncs it with tags in your Evernote apps. So far the closest app to that is [Lavera](https://laverna.cc), which is just markdown, but is worth listing I think.

**Comment by Treora** [comment]
Integration into an ecosystem of tools is indeed a primary goal. As for storage&syncing, [RemoteStorage](https://remotestorage.io/), as Laverna uses, could play a role in this. But so could [Dat](https://datproject.org/), [SoLiD](https://solid.mit.edu/), or other solutions for web-writability.

Keeping track of and looking for potential integrations with related projects is an ongoing effort; I am closing this issue however, as it seems inactionable and potentially never ending, and different types of integrations would deserve separate discussions.
