### ISSUE TITLE
error on freeze drying website with wrong <link href>

### ISSUE THREAD

**Issue by pierstitus** [WebMemex/webmemex-extension#137]
Archiving the website https://www.vikingdome.com/blog/portfolio-item/aura-dome-garden-pod/ gives an error. The freeze drying code fails because in the header `<link rel="publisher" href="https://Specializuojamėsgeodeziniųkupolųbeiįvairiųkonstrukcijųprojektavimeirgamyboje.Teikiameprojektavimo,konstrukcijųgamybosbeimontavimopaslaugas."/>` has an invalid URL.

**Comment by Treora** [comment]
Thanks, I stumbled on the same problem recently. Tracked in https://github.com/WebMemex/freeze-dry/issues/41

**Comment by Treora** [comment]
Fixed in v0.3.3!
