### ISSUE TITLE
Search memory in address bar

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#14]
Two possible approaches:

1. Use the [`omnibox`](https://developer.chrome.com/extensions/omnibox) API, like [WorldBrain](https://github.com/WorldBrain/Research-Engine/)/[Falcon](https://github.com/lengstrom/falcon). Currently only possible in Chrome|ium, and only works when the user enters a specified prefix, but it does allow to directly display results as suggestions.
2. Define a search engine provider. If extension URLs are not supported as search providers, we can provide a fake URL, requests to which we redirect back to the extension. Downside: suggestions would probably not be supported as they seem not redirectable from the webRequest API. Also, switching default search engines is a hassle in Chrome|ium, though easier in Firefox.

Neither solution is really satisfying.

**Comment by blackforestboi** [comment]
Another option would be to make it like Pinboard. So if users search via the address bar they automatically land on a search engine (maybe google) and then get (the first 5) results displayed on the side or as the first results. 

Also the missing API endpoint for the address bar will be resolved with the new FF53 (release 23. april). The problem then still remains for other browsers like safari or vivaldi.

**Comment by Treora** [comment]
Indeed an option to peg onto a user's existing web search (though, again, not really satisfying).

None of these options exclude each other, and all of them are compromises just to provide somewhat more convenient, quicker access to something that is already accessible in another way. I guess some user research may be helpful here, and whatever works suffices in the meantime.

**Comment by blackforestboi** [comment]
I think its best to just go with the way Falcon/WorldBrain does it right now. Accessing search it in the Omnibar with the command w+tab/space.

The code, giving inspriation for that can be found here: https://github.com/WorldBrain/Research-Engine/blob/master/src/js/background.js#L17
The functions involved: 
 - chrome.omnibox.onInputChanged.addListener(omnibarHandler);
 - chrome.omnibox.onInputEntered.addListener(acceptInput);
 - omnibarHandler
 - suggestionsComplete
 - makeSuggestions
 - dispatchSuggestions

## Addition to the existing code
The first result should be a link to the full results page of the same query.

**Comment by Rohanhacker** [comment]
can I work on this I am a newcomer ?

**Comment by blackforestboi** [comment]
Yes, good one. As discussed in the call, feel free to take it on!

**Comment by Rohanhacker** [comment]
How does it look?
![screenshot from 2017-03-11 18-13-03](https://cloud.githubusercontent.com/assets/9512969/23823356/a361dda2-0686-11e7-8b29-7d8ed0accc52.png)

**Comment by blackforestboi** [comment]
Nice! that was quick. Looks great. 
As a bonus it would be great to show the visit time as well. so like `10/3/2017 3:30pm`, if that is easily possible. 
Also it would be cool, if the first result would show something like "Show all results (10)" Whereas 10 would be the number of results that have been found and it would link to the search overview with the same query and the 10(?) results. 

Does that make sense?

**Comment by Treora** [comment]
Nice indeed!
>
> As a bonus it would be great to show the visit time as well. so like
> |10/3/2017 3:30pm|, if that is easily possible.
>
I suggest to use src/utils/nice-time.js for the date/time, so it shows
the time for recently viewed items, and only the date for older items
(its behaviour could still be tweaked). The rest of the code uses this
too, making it nicely consistent.
>
> Also it would be cool, if the first result would show something like
> "Show all results (10)" Whereas 10 would be the number of results that
> have been found and it would link to the search overview with the same
> query and the 10(?) results.
>
Good idea.

**Comment by Rohanhacker** [comment]
time can be easily done but I am not sure how one can modify redux store from a background script ??
