### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by clmay** [WebMemex/webmemex-extension#140]
As a user, I want to be able to use keyboard shortcuts to:

- Snapshot current page
- Open "all snapshots" page

Additionally, on pages that do not support snapshots, I want the "take snapshot" shortcut to have no effect.

I will try to find time to dig into [Codetour.md](https://github.com/WebMemex/webmemex-extension/blob/master/Codetour.md) to see how the extension works.

If anyone has thoughts on how to implement this, please let me know. I've always liked the Settings feature for the Firefox extensions [Video Speed Controller](https://github.com/codebicycle/videospeed), would hope to implement something similar.

**Comment by Treora** [comment]
Fantastic. Note that the manifest already [defines](https://github.com/WebMemex/webmemex-extension/blob/7293f3fc210f1dc08c8a59788a582e9321dadf2e/src/manifest.json#L26-L39) two shortcuts:
- `Ctrl+Y` to open the overview (configured [here](https://github.com/WebMemex/webmemex-extension/blob/7293f3fc210f1dc08c8a59788a582e9321dadf2e/src/main/background/menus-and-shortcuts.js#L81-L84))
- `Alt+M` to store the page. Actually, it just opens the popup menu. If desired, we could make it store the page instead, but I am not sure we can do both (could the popup somehow detect how it was opened, i.e. by click or by shortcut?). At least, we could make the popup put focus on the ‘take snapshot’ button when opened, so one can press `Alt+M, Space` to take a snapshot.

When I configured this (roughly three years ago, maybe things changed) I found it difficult to get this working well. If the shortcut conflicts with another one, it appears to silently be ignored, and it seemed impossible to know if this is the case, nor to let the user change the shortcut either. I chose the key combinations empirically as these seemed to work in both Firefox and Chromium (at least on Linux).

Now you remind me of its existence, I updated the code tour a bit. :)

**Comment by Treora** [comment]
> At least, we could make the popup put focus on the ‘take snapshot’ button when opened, so one can press `Alt+M, Space` to take a snapshot.

I implemented this change in commit 8304985. Does this solve your needs?

Closing this issue for now; but feel free to follow up if you have a better solution!
