### ISSUE TITLE
Download snapshot database to another machine

### ISSUE THREAD

**Issue by kvgc** [WebMemex/webmemex-extension#145]
Hi,
How do I download all my snapshots from one machine and add it to another machine? 
I am able to download the html but is there a way to upload it back to the extension?
This seems like a simple thing that could be done but I can't seem to figure it out. 
Thanks!
--
kvgc

**Comment by Treora** [comment]
Hi, sorry there is no function to import snapshots back into the extension.

As background info: Storing snapshots inside the extension appeared unreliable (my Firefox repeatedly deleted all my snapshots), and it increasingly felt like a bad design pattern anyway (as the data is hidden in an app), so at some moment I gave up on it and started storing pages as downloads instead (see [this blog post](https://blog.webmemex.org/2018/12/09/personal-web-archives-a-report/#tool1storingawebpageasafile) for some design philosophy). I did not remove the feature to store snapshots in the extension (for existing users using the overview/search features) but did not develop it further.

A function to import files back into the extension could of course be made, but I’d personally not want to invest much time in it, as I rather look at ways to get the desired functionality (such as a snapshot overview and full-text search). Note that these functions might not need to be provided by the same tool: e.g. one can use any file manager’s full-text search inside the Downloads folder to find a snapshot.

In any case, nice to hear that you find this software useful, and sorry for its incompleteness!

**Comment by kvgc** [comment]
Hi, Thanks so much. That makes sense. 
I really like the extension's idea and would love to integrate note taking into it.  
I have a working prototype of a note taking web extension (https://github.com/kvgc/WebResearcherJS-extension) that I was able to put together with a friend of mine.  But I like the way webmemex allows you to search through the webpages that have been saved. I think that's really powerful. I have been meaning to incorporate such a save and search interface for the note taking extension. 
Would love to get your thoughts on possible ways to integrate with webmemex if that's something you might be interested. I will consider reading the codetour in the meantime...
