### ISSUE TITLE
Wrong page is captured

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#15]
If the tab's location changes before loading of some page completes, the next page's load event will trigger the analysis of that former page, which then thus gets the wrong page's title, screenshot, etcetera.

Should be fixable in `tab-events` (see 043be83).

**Comment by gastonche** [comment]
Please i would like to know if this issue is still a problem, so that i may work on it. Thanks

**Comment by Treora** [comment]
Still to be fixed indeed, thanks for getting at it. Not sure exactly which event to listen to to be 100% sure the promise is cancelled when the page is changed, so have a look first what options are available.

**Comment by gastonche** [comment]
okay i'll try various options until we get to a good fit

**Comment by Treora** [comment]
Fixed by #62.

**Comment by blackforestboi** [comment]
Congrats @gastonche to your first Merged PR :)

**Comment by gastonche** [comment]
Thanks @oliversauter
