### ISSUE TITLE
UI for bookmark&history import

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#17]
A user interface to start and stop importing of bookmarks & history, and watch its progress.

See description here: https://github.com/WorldBrain/Research-Engine/issues/92

**Comment by reficul31** [comment]
I would like to take up this task. From what I understood from the description and the corresponding ref link we are supposed to make a UI/UX for importing the bookmarks and history from the back end and show the progress.
@Treora 
I have a couple of questions regarding the issue.
1. The ticket is regarding UI/UX. Am I correct to assume the back end is done?
2. Where should the components be placed?

According to me the approach to follow.
1. Make the component design. Get it approved.
2. Make the components.
3. Connect to the backend(if any)
4. Document for future devs

**Comment by blackforestboi** [comment]
@reficul31 this is a somewhat bigger task and I would be rather giving it to a newcomer, as there are still some people we want to see how the collaboration works. 
Thanks for your proactivity to help on that.  

The backend is not fully done, so for now, a first version would just be a dummy page work-flow.

**Comment by alxmiron** [comment]
@oliversauter I'm a newcomer and I'd like to work on this feature. 
Task: implement an extension page for importing browser bookmarks and history into db, with startand stop buttons, progress animation.
Proposed page layout: like on setting page
![memex-blacklist](https://cloud.githubusercontent.com/assets/10484318/23751396/d1810afe-04d9-11e7-9dc5-577140f627bb.gif)

**Comment by blackforestboi** [comment]
Hey Alex!

thanks for the phone call today and for your quick engagement. 
Looking forward to your implementations. 

[Here](https://github.com/aquibm/webmemex-extension/commits/master) is the code of @aquibm that includes these designs. 

Best,
Oliver

**Comment by AlexMarvelo** [comment]
#65

**Comment by Treora** [comment]
Closing this issue; off the roadmap.
