### ISSUE TITLE
Editable blacklist/'forgetlist'

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#20]
As a user, I do not want my computer to remember visits to, ehm, well, certain websites.

The settings page should have an editable list of domain names which are to be ignored. Each entry could be a regular expression to provide more power to power users.

I noticed the word 'blacklist' appeared a bit confusing to some people (we do not block the pages). Perhaps call it 'forget-list', 'ignore-list', or something else?

**Comment by blackforestboi** [comment]
I like the wording "Ignore-List"

Question we may consider: Should we automatically delete all pages that have been blacklisted in retrospect as well?

**Comment by Treora** [comment]
> Should we automatically delete all pages that have been blacklisted in retrospect as well?

Good point. Would be good to make that possible, but it would preferably first ask whether to "delete 62 matching pages from the memory". Else I would probably erase half my memory some day through a silly regex mistake. ;)

**Comment by blackforestboi** [comment]
> but it would preferably first ask whether to "delete 62 matching pages from the memory"

Good idea. Maybe just with a simple browser prompt that can be cancelled? 

![](https://i.stack.imgur.com/gyxZZ.png)

**Comment by Treora** [comment]
Something like that, I suppose. Though preferably with something slightly prettier (plenty of UI libraries provide question dialogs). It could also be less obtrusive by the way, I now imagine a small note below the list asking "Also remove 62 matching items from memory? [Yes] [No]". Sorry for fussing over details already.

**Comment by blackforestboi** [comment]
hehe yeah sure :) I am not thinking about that specific UI, was just as an example. 

> "Also remove 62 matching items from memory? [Yes] [No]"

Sounds good to me. Simple short and to the point.

**Comment by blackforestboi** [comment]
@aquibm 
Do you plan to take on the UI and the logic part of this task?
With the logic part I mean the actual storage of the blacklist items to any form of storage.

If yes, we need some clarification on how you aim to store the items, an info needed for another task: The actual enforcement of the blacklist. 
This would be a function that tests a URL if it should be stored or not. For that we need to know how the list of items to check is loaded. 

Just that its not left unsaid: Some options we talked about in the past would to simply store it in local storage, or to also store it to PouchDB. The latter option would have the advantage, that we can replicate the blacklist settings as well (without additonal work), when the DB is replicated (i.e. on the server or to another installation)
Though this part does not solve the question of the format.

**Comment by aquibm** [comment]
@oliversauter So far I've been working on the UI & user interactions for the blacklist. I'm planning on leaving persistence until the end but I believe the idea is to use redux-pouchdb to persist state.

**Comment by Treora** [comment]
Closing this issue, as automatically logging visits is not on the roadmap anymore.
