### ISSUE TITLE
Forget individual pages

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#21]
One should be able to remove individual pages/visits from their memory. At least from the history/search overview, through a context menu, or (fancier) by dragging it to a bin. Perhaps also through a menu on the to-be-forgotten page itself.

When we have implemented a blacklist (#20), we can also ask whether to enlist the domain of the removed page and/or forget all pages from that domain.

See also https://github.com/WorldBrain/Research-Engine/issues/46.

**Comment by blackforestboi** [comment]
> When we have implemented a blacklist (#20), we can also ask whether to enlist the domain of the removed page and/or forget all pages from that domain.

@obsidianart had a few ideas how to make this flexible. I can't recall them though.

**Comment by obsidianart** [comment]
I didn't have any specific improvement, we had a conversation where I said I can't use the plugin because of the security policy I'm under unless you disable any website with a login.
I think we can slowly improve the "disable by default" and ask the user something like "Do you want to index your emails" etc. Till the moment in which we can guarantee security I wouldn't index any personal data (gmail, github, Jira, whatsapp, FB, etc).

**Comment by blackforestboi** [comment]
I mean you have been mentioned something regarding multiple options "regex, domain, url". You were talking about a way to do it that would make it better extensible with rules.

**Comment by wimpykid26** [comment]
For now it's just deleting multiple occurrences of the page from the db right?.
After the blacklist is done, we'll have to make it flexible using RegEx?.
Can I work on this?.

**Comment by blackforestboi** [comment]
@wimpykid26 

Thanks for your enthusiasm to help :)
>For now it's just deleting multiple occurrences of the page from the db right?

Yes, for now it would be to block and delete everything coming from a specific domain. This would be the background logic to what @aquibm is working on in: https://github.com/WebMemex/webmemex-extension/issues/20

I just invited you to our slack channel, there you can directly contact @aquibm. Please be so kind to introduce yourself quickly in the #intros channel and have your conversation about this issue in the public #merger channel. Thanks :)

**Comment by Treora** [comment]
> > For now it's just deleting multiple occurrences of the page from the db right?
> 
> Yes, for now it would be to block and delete everything coming from a specific domain. This would be the background logic to what @aquibm is working on in: #20

Small apparent misunderstanding here: I think @wimpykid26 meant that right now there is no blacklist, so the feature would just remove the existing occurence(s) of the page from the database. Right? This 'forgetting' part may be a good thing to already implement, and is independent of the blacklisting part.

Only after the logic for blacklisting has been created (have to synchronise plans with Aquib for this), the forget-this-page feature can be augmented with the blacklist-this-page functionality.

**Comment by Treora** [comment]
Restating @oliversauter's question from #48 (duplicate) here:
> Although here might come the question, if we now automatically delete the page object and all the visit objects as well, or just a single visit?
> I would go for the first one.

I see at least a few things one may desire to do:
- removing all traces of having visited a site (one may also want to remove it from browser history then..).
- deleting the page contents, not necessarily the knowledge of having been there, because of sensitive data in the page.
- deleting a single visit to a page, to clean up clutter from one's overview.

I would say let's choose any one for now and see in practice what users need most.

**Comment by Treora** [comment]
And of course there are the possibilities that we can fulfil when we keep a blacklist of websites that are to be ignored:
- deleting all pages from a website (domain), and ignoring that site in the future.

**Comment by wimpykid26** [comment]
@Treora from a technical perspective, could you please tell me where to start
From what I grasped :
> removing all traces of having visited a site (one may also want to remove it from browser history then..).

Get url and title of the page to be deleted, match them against corresponding entry in pouchdb and remove them.

> deleting a single visit to a page, to clean up clutter from one's overview.

Removing only a single entry would require the visittime, match them against the db and then delete that entry.

**Comment by blackforestboi** [comment]
@wimpykid26 @Treora 

I would assume that the most common use case would be that a person wants to have everything removed about that page, all visits and the data. At least for now, I assume it is less likely that a person wants to do it to clean up, hence the desire to only remove a single visit.

**Comment by Treora** [comment]
>     removing all traces of having visited a site (one may also want to
>     remove it from browser history then..).
>
> Get url and title of the page to be deleted, match them against
> corresponding entry in pouchdb and remove them.
>
You could probably find all pages with the same URL (there is already a
function for this in `src/search/find-pages`), find all visits to these
pages, and delete them all.
>
>     deleting a single visit to a page, to clean up clutter from one's
>     overview.
>
> Removing only a single entry would require the visittime, match them
> against the db and then delete that entry.
>
Each visit has an `id`, just deleting that visit would do for this goal.
However, as Oliver just said, this may not be the most important usage
scenario; but it may still be good as a simple task to try tackle first.

Either way, take it easy, and try to understand both the problem and the
code first, instead of directly focussing on adding a feature. Try make
one or two solutions and share them with us when you think you got
something that works nicely.

**Comment by wimpykid26** [comment]
Sure. Will keep you updated . Thanks :)

**Comment by wimpykid26** [comment]
Hello @oliversauter @Treora . What I did was:

call `searchPages` present in `src\search\find-pages` which returns all the entries corresponding to a give query.

mapped them into an array containing every doc._id and doc._rev.

for each doc._id call db.remove() and delete corresponding entry from the table.

![screenshot from 2017-03-07 00-45-41](https://cloud.githubusercontent.com/assets/20013195/23625769/4ca5b326-02d0-11e7-8793-9ed6507adc77.png)

Visited facebook 3 times.
Called the function
After getting deleted, no entries left in db.

Am I missing something? .

**Comment by wimpykid26** [comment]
@Treora any thoughts?

**Comment by Treora** [comment]
Instead of an array of id+rev, you could also just pass the whole page doc to `db.remove`; may result in slightly simpler code.

I noticed I was wrong about what I said earlier:
> You could probably find all pages with the same URL (there is already a function for this in `src/search/find-pages`), find all visits to these pages, and delete them all.

This function is still to be added by the deduplication PR (#60), so it will be there soon. You could try to rebase onto that branch and use it already.

When you have code that you think is good enough for merging (working, commented and thoroughly cleaned up), feel free to open a PR, and I will review.

**Comment by Treora** [comment]
A trash-bin button has been added in the new layout (#55), so it should be little effort to rebase&clean up #67 and connect it to that button.

**Comment by blackforestboi** [comment]
@morozow relevant to you.
