### ISSUE TITLE
Data conversion from current WorldBrain extension

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#24]
The current user base stored data to local storage. Now we implemented PouchDB. Therefore we need the ability to transfer the data from LS to PDB as soon as the extension updates for them.

**Comment by blackforestboi** [comment]
Some basic work here has already been done by @arpitgogia. 

The function can be found in WorldBrain's background.js `transferToPouch()` function

Problem I see is, that this function is activated everytime the extension updates, which leads to unecessary processing. I believe in the API specs there is an endpoint defining events like "onupdate", which could possibly be used to trigger it once the update runs.

**Comment by Treora** [comment]
@oliversauter: Removing this from this list, as this is worldbrain-specific and not affecting our common code base. If you need support in the webmemex code e.g. to add hooks to trigger your migration code, that could be handled in a new issue.
