### ISSUE TITLE
Infinite scroll in overview

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#25]
When reaching the bottom of the overview, load more (= older) items.

Note that when a search query is applied to filter the items in the overview, the question becomes more difficult, because then there are two (abstract) dimensions that could be expanded: load older results, or load less 'query-relevant' results. We could start with expanding just one dimension, namely whichever dimension things are ordered (currently time, but sorting by query-relevance could also be an option).

**Comment by blackforestboi** [comment]
@aquibm 

You mentioned something regarding pagination vs. infinity scroll in the last call, if I am not mistaken? I just can't recall what it was.

**Comment by aquibm** [comment]
I think it was Mario who brought up using paging over infinite scroll to allow the user to remember what page their result was on when searching repeatedly for the same query. I still don't understand how that would work though because as @Treora pointed out, history is constantly being updated.

I think a good option would be to use infinite scroll + fuzzy time range filters (yesterday, this week, this month, etc)

**Comment by ChhaviSharma4** [comment]
Hello @Treora ,
I was thinking of taking up this issue.Could you please elaborate on the requirements. According to the current code, doesn't the search query produce the list of items filtered according to time?

**Comment by Treora** [comment]
Hi Chhavvi, great that you want to help. The search code is a bit complex though, so I recommend to read it through first, if you did not do so already, and see if you understand the whole flow (you have to be comfortable with `pouchdb`/`pouchdb-find`/`pouchdb-quick-search`, and javascript Promises).

Currently the code does not filter the search results by time. It only searches by text query, and then orders the results by time. I don't see a way in `pouchdb-quick-search` to limit the search query to results from a particular time range, but we could do the full search, and afterwards filter its results by time.

I would however avoid the complexity around search for now, and start with the easier case: when no search query has been given. This just gets the most recent visits in descending order. Getting and appending less recent visits to this list when reaching the bottom would be a good improvement already.

**Comment by blackforestboi** [comment]
> but we could do the full search, and afterwards filter its results by time.

This is how @arpitgogia implemented it in the WorldBrain code: https://github.com/WorldBrain/Research-Engine/blob/master/src/js/background.js#L174

**Comment by SudhanvaMG** [comment]
Hey , if this is not taken , i would like to work on it .

**Comment by blackforestboi** [comment]
I was just told by @arpitgogia that Chhavi also has her exams period in the coming 2 weeks. So she wont be able to take it on. Is that correct @ChhaviSharma4?

If yes, I would suggest we give Sudhanva the "go" to take it on.

**Comment by SudhanvaMG** [comment]
Ok . I will work on this .

**Comment by ChhaviSharma4** [comment]
Yes sure @SudhanvaMG! I am sorry @oliversauter since I will be unable for this duration.

**Comment by Rohanhacker** [comment]
Hey can I change ResultList to a class component as I have to get scroll position for last li for infinite scroll. for eg. when last element get to a certain distance from top then it'll get prev 30 results and append it to searchResults ? @Treora @oliversauter

**Comment by Treora** [comment]
@Rohanhacker: sorry I never replied, seeing your question now. Of course things can be changed if needed. I would be happy to hear if you got stuff working.

If nobody is on this issue, I may try tackle it myself sometime soon, the overview feels a bit incomplete without this.

It seems there are many libraries around (e.g. [react-infinite-scroller](https://github.com/CassetteRocks/react-infinite-scroller)) that could be used to abstract the feature. Or at least they may be good examples to borrow ideas from.

**Comment by blackforestboi** [comment]
@morozow relevant to you

**Comment by Rohanhacker** [comment]
I'll try to make it work and send a pr soon

**Comment by obsidianart** [comment]
I dropped react-infinite-scroller recently in favour of react waypoint, it's a simpler implementation of the concept and much easier to adapt to what you want

**Comment by Treora** [comment]
Was fixed by #106; merge commit a74943a.
