### ISSUE TITLE
Batch fetch&analyse pages

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#28]
Download a page to analyse its content and update its entry in the database.

Intended for getting more knowledge about imported browser bookmarks&history. See WorldBrain's corresponding [issue](https://github.com/WorldBrain/Research-Engine/issues/92).

**Comment by bohrium272** [comment]
Granted we have to obtain page content using `XMLHttpRequest`, there would be a whole lot of requests. I was thinking if there is any library/module to do it with optimal performance. 
Found these:
* https://github.com/volpav/batchjs
* https://github.com/socialradar/batch-request

If we can work something out here, we should use it for WorldBrain too.

**Comment by Treora** [comment]
There will be a whole lot of requests indeed; but each to different servers, and servers that are not ours, so unfortunately those libraries seem of no use in our case.

What I am thinking of is to make a function `fetchAndAnalyse` that, given a url, will end up putting a `page` object in the database that is as similar as possible to what would have been produced if the user would just have visited that page manually.

Having such a function, we could then apply it to every url in any given list of urls, in particular the urls imported from one's browser bookmarks and browser history. This would be the 'batch' part, and it may take a while for larger lists, so the main tasks here are to make it possible to pause and resume the process, and to inspect its progress.

But the first task is not the batch aspect, but to fetch&analyse a single page. We could start with just storing the html (for html documents), extracting its plain text for indexing. Later we can also run analysis on it to extract metadata, main text content, ~~maybe make a screenshot using [PhantomJS](http://phantomjs.org/)~~ or such.

Now I am thinking of it, I may be making it too complex; if we are writing this to run in the browser anyway, we could skip the PhantomJS, and avoid having to make a separate analysis pipeline for these pages that are fetched in the background. We could simply open the url in a tab programmatically, have it be analysed as usual, close the tab programatically, and then continue with the next one. It also makes the process very visible to the user, which may be a good thing, though there may also be complications with this approach.

We could start with implementing whatever seems easiest to implement, and experiment a bit to get a better feeling for it.

**Comment by blackforestboi** [comment]
> extracting its plain text for indexing.

In the WorldBrain code I used a code snipped that I extracted from a library called textract:
https://github.com/dbashford/textract

The cool thing is that the library is capable of reading all sorts of formats as well. I just used the HTML part. 

HTML, HTM
Markdown
XML, XSL
PDF
DOC, DOCX
ODT, OTT (experimental, feedback needed!)
RTF
XLS, XLSX, XLSB, XLSM, XLTX
CSV
ODS, OTS
PPTX, POTX
ODP, OTP
ODG, OTG
PNG, JPG, GIF
DXF
application/javascript
All text/* mime-types.

The code I used to extract text content was this: https://github.com/WorldBrain/Research-Engine/blob/master/src/js-browserify/html.js

Although I do not advise using my version of it, as I removed special characters, this has shown to cause problems with languages using "ä, ü, é"....etc. 
But the original one supports it.

**Comment by bohrium272** [comment]
Yes a `fetch&analyse` function would suffice. 
>  We could simply open the url in a tab programmatically, have it be analysed as usual, close the tab programatically, and then continue with the next one. It also makes the process very visible to the user, which may be a good thing, though there may also be complications with this approach.

I think this would not be particularly user friendly. Assuming a user has like a 1000 pages, I don't see how this approach would be good. What we did in Research-Engine was obtain the raw HTML of the page using `XMLHttpRequest` and then supply it to Falcon's already implemented processing architecture. 

I think what @oliversauter has suggested would work well.

**Comment by blackforestboi** [comment]
> I think this would not be particularly user friendly. Assuming a user has like a 1000 pages,

Actually a regular history has around 9-10k and the amount of bookmarks I hear were about 3k max. 
I also don't think that this would be a good option. (Tab open and close)

In the WorldBrain code, I simply took the metadata from the history element provided by the history.api and only added the content to the same format as with a regular visit. So that should not be a big problem I assume.

@Treora When importing the history elements from the API, you store them in a shell containing title, visit times (etc) right? If people would want to index them then as well, we would just go through the current database and look for URLs that have not yet been downloaded, correct?
So we basically would not do much more than downloading the HTML, stripping out all the text and then storing that text to the already existing object?

**Comment by Treora** [comment]
The textract tool looks nice, thanks Oliver. Unfortunately for most of the file types it requires native software; it is meant for running in NodeJS, not in a browser.

For getting just the html and all its text, it is easy to make a fetch in the background. I was just thinking out loud about easy ways to get as much out of a page as when visiting it manually, such as taking a screenshot and extracting the main text through Readability. Now we will probably have to use jsdom or so to run Readability in the background process. That is fine too, but it would be easy to just open the page in a normal tab, to not have to create a second analysis pipeline.

And of course, I think it would be great to see what the computer is doing. How awesome would it be to have a batch fetch process resemble the [first scene with Neo in The Matrix](https://www.youtube.com/embed/LI_4v__IVTg?rel=0&autoplay=1&end=30)? :sunglasses:

**Comment by blackforestboi** [comment]
> The textract tool looks nice, thanks Oliver. Unfortunately for most of the file types it requires native software; it is meant for running in NodeJS, not in a browser.

ok then it will come in handy as soon as everything is running on the server, i guess?

> Now we will probably have to use jsdom or so to run Readability in the background process.

When we do it as a background-fetch for the import, we have to be aware, that we cannot use 'document.body.innerText'. Hence we will lose a lot of text content for non-articles when just using Readability. This was the original reason I used the textract library (specifically the HTML parser)

We could use it in combination again, like done now (readability + body.Innertext (in that case html.js from textract))

> That is fine too, but it would be easy to just open the page in a normal tab, to not have to create a second analysis pipeline.

Thinking out loud: Wouldnt this lead to a lot of performance problems, because every page has to be rendered? It already takes quite a while to download X amount of pages without rendering them.

In general this analysis pipeline is later used for other things as well (like importing pages from other bookmarking services). Being able to download pages in the background seems to me like the more sustainable option. 

Also Chhavi just messaged me that they would like to take on the classifier and Schemafy the web projects for RGSoC, means the pipeline is a good foundation to make those processes run in the background on the fetched HTML code of an URL. 

> How awesome would it be to have a batch fetch process resemble the first scene with Neo in The Matrix? 😎

Hehe, wouldnt that be solved with just a list of urls that are processed and their statuses?

**Comment by Treora** [comment]
> ok then it will come in handy as soon as everything is running on the server, i guess?

As discussed out of band, running everything on the server is not currently on the roadmap.


> Hence we will lose a lot of text content for non-articles when just using Readability

I did not mean to *only* use Readability, we can still grab the plain text as well, either by doing some manual html-stripping (like or with the textract script) or grabbing `body.innerText` from jsdom if we would use it anyway.

Currently we store quite a lot of overlapping data for each page though, and I would like to store even more raw html data, so the approaches of what (and how) to store should be revised some moment. Consider it ongoing experimentation.


As for the performance of rendering each page; yes that may be expensive, so the question is really what the goals are, and how much can be achieved with a limited amount of developer time. My suggestion of rendering pages in the background script with PhanthomJS was just silly by the way — it is back-end software. Possibly later if we do end up running stuff as a native application or on one's server though!

**Comment by bohrium272** [comment]
Have we reached an algorithm we would like to try out?

**Comment by Treora** [comment]
I would start in any case with making the functions to fetch the file, create a page doc in the database, and perhaps just dump the complete file in it for simplicity. If there is a clean setup for that (open a PR to ask for a review), we can start plugging in different functions for different types of analysis, at least grabbing the plain text. For that, I would give [jsdom](https://www.npmjs.com/package/jsdom) a try, to first just grab `body.innerText` and later also invoke Readability; I wonder how fast or slow it is.

**Comment by colsondonohue** [comment]
To me, it seems like this would be used immediately upon import of history/bookmarks, where there would already be pageDocs and visitDocs in the db. 

> What I am thinking of is to make a function `fetchAndAnalyse` that, given a url, will end up putting a page object in the database that is as similar as possible to what would have been produced if the user would just have visited that page manually.

Instead of passing in the url, the function could take an object with the url and the id. That way the function would still get the url, but would also have the id in order to modify the existing db entry. What I'm thinking is that in `importHistory` (and later `importBookmarks`, etc.) after the documents are added, the next `.then` will execute the page analysis.

Calling jsdom.env on a url will yield the DOM of that page, complete with `document` and `window` objects. We could then use much of the existing analysis pipeline without having to open a new tab. The screenshot and favicon gathering functions are the only part that would require a `tabId`, so I'll have to think more about how to get around that.

**Comment by Treora** [comment]
> To me, it seems like this would be used immediately upon import of
> history/bookmarks, where there would already be pageDocs and visitDocs
> in the db.
>
That would be the primary use indeed.
>
>     What I am thinking of is to make a function |fetchAndAnalyse|
>     that, given a url, will end up putting a page object in the
>     database that is as similar as possible to what would have been
>     produced if the user would just have visited that page manually.
>
> Instead of passing in the url, the function could take an object with
> the url and the id. That way the function would still get the url, but
> would also have the id in order to modify the existing db entry.
>
It could indeed accept a page (or pageId) instead of a url. I am however
not sure if the imported page should be updated.. Working on
deduplication, I came to think it is cleaner to create a new page object
instead, as you will download the current version from the URL, not the
one that was originally visited and that the page from the history
represents (unless we can really be sure we get the intended old version
through some Memento-speaking archive or something). The historical item
could have a link to the downloaded page.
>
> What I'm thinking is that in |importHistory| (and later
> |importBookmarks|, etc.) after the documents are added, the next
> |.then| will execute the page analysis.
>
I would separate the two processes and have control at higher level call
importHistory and perhaps then start batch downloading. The download
process can take ages, so should probably be separate a background
process rather than a promise to wait for. We could keep a queue of
pages/URLs to be downloaded in the database, so this download process
can be interrupted and resumed any time.
>
> Calling jsdom.env on a url will yield the DOM of that page, complete
> with |document| and |window| objects. We could then use much of the
> existing analysis pipeline without having to open a new tab. The
> screenshot and favicon gathering functions are the only part that
> would require a |tabId|, so I'll have to think more about how to get
> around that.
>
I suspect screenshots is out of question, unless we try experimental
stuff like html2canvas <https://github.com/niklasvh/html2canvas> to
render the page in the background. We could change the favicon grabber
to get its URL from the html itself (or use default '/favicon.ico'
otherwise).

I'd be glad to hear the results if anyone feels like doing some research
into any of these parts (jsdom+metadata/readability, favicon, maybe
html2canvas).

Maybe we should first get a solid download process with good
error-handling working though.

**Comment by colsondonohue** [comment]
@Treora Okay, your approach makes a lot of sense. I can get started on that. 

>We could change the favicon grabber
to get its URL from the html itself (or use default '/favicon.ico'
otherwise).

I found [an npm module](https://www.npmjs.com/package/favicon) to retrieve the url of a favicon given the url of a webpage. Could be preferable to trying to reinvent the wheel.

**Comment by blackforestboi** [comment]
>  I came to think it is cleaner to create a new page object
instead, as you will download the current version from the URL, not the
one that was originally visited and that the page from the history
represents

How is this handled when the user is searching with a time filter? When I am searching for a page, I know I have visited it, say 2 months ago. Do I find it when filtering for the "2 months ago" or is it stored with a time stamp of the time of the import?

**Comment by Treora** [comment]
>     I came to think it is cleaner to create a new page object
>     instead, as you will download the current version from the URL,
>     not the
>     one that was originally visited and that the page from the history
>     represents
>
> How is this handled when the user is searching with a time filter?
> When I am searching for a page, I know I have visited it, say 2 months
> ago. Do I find it when filtering for the "2 months ago" or is it
> stored with a time stamp of the time of the import?
>
Fair question, but when searching for when you /visited/ a page, I
suppose we should filter the by timestamps of the /visits/, not the
pages. A page could also have been visited multiple times, so its single
timestamp is not such a meaningful thing in that regard. I regard it
mainly/merely as a version tag for URLs.

The search process becomes a bit more complex through such a design that
keeps pages and visits separately, but this type of complexity can be
dealt with by using the right databases and index structures. Or you may
have to issue two queries instead of one, but that's okay.

**Comment by Treora** [comment]
@colsondonohue: Hi, you had some good thoughts on this issue; last I heard was that you were working on a 'background processing pipeline', and trying to work around some issue with jsdom. I wondered if you continued with this, or if you moved on to other things, if perhaps your code is available for others to learn from?

**Comment by poltak** [comment]
> What I am thinking of is to make a function fetchAndAnalyse that, given a url, will end up putting a page object in the database that is as similar as possible to what would have been produced if the user would just have visited that page manually.

I like this idea (using an ID as the arg as @colsondonohue suggested) and being able to queue up calls to this `fetchAndAnalyse` (so also interested to see if @colsondonohue made any progress). 

As it's been discussed that it should produce a similar outcome as visiting a page manually, this got me looking into the current `page-analysis` code that does that. If I'm understanding it all correctly, at the moment that module grabs the page text and metadata using RPCs via an interface that was exists in the codebase. In this thread there's lots of mention of using XHRs to do the same thing.

What's the reason behind using the RPCs in the current `page-analysis`? 
And I suppose that leads to the question: can the `fetchAndAnalyse` function just reuse that `page-analysis` module's logic?

I'm still trying to wrap my head around all this, so sorry if I have missed something and those questions have obvious answers.

**Comment by poltak** [comment]
Furthermore @Treora: In response to @colsondonohue's suggestion for an ID being passed into `fetchAndAnalyse`, you said:

> It could indeed accept a page (or pageId) instead of a url. I am however
not sure if the imported page should be updated.. Working on
deduplication, I came to think it is cleaner to create a new page object
instead, as you will download the current version from the URL, not the
one that was originally visited and that the page from the history
represents

Saying this, what is the intention for the existing page doc if the `fetchAndAnalyse` function should create a new page doc? 

I originally understood this to be: the `import-history`/`import-bookmarks` module will create a "shell" page doc for each given page. This shell contains URL, title and some other easy-to-get data, then _sometime later_ the `fetchAndAnalyse` will grab further data to "fill-out" the shell. If you don't want to update the existing page doc, should we maybe have another doc type, like `visit`/`bookmark` that references a given `page`?

**Comment by Treora** [comment]
> What's the reason behind using the RPCs in the current page-analysis?

RPC here means calls between the background process and content script, nothing really remote. The background process organises the logging and storage, but only the content script can access the DOM, so they have to send messages back and forth, which is hidden behind the RPC abstraction. The RPC seems to hit a bug in newer Firefox versions by the way, try it on Chrome|ium for now.

> can the fetchAndAnalyse function just reuse that page-analysis module's logic?

Would be nice if parts can be shared, but it would require some thinking and reorganisation. Since the fetched pages don't have a tab, the analysis functions would have to work on either a tab or an 'invisible page' (blob / jsdom object / something else)? Screenshots would not be feasible anyway.

I am actually still considering the arguably hacky alternative approach ([discussed above](https://github.com/WebMemex/webmemex-extension/issues/28#issuecomment-282551298)) where we programmatically visit the to-be-fetched URLs in tabs, so we can run the exact same pipeline without changes. Also javascript would be executed, so client-side-generated sites would be captured properly. Background fetching would be nice though, if it is not too much effort.

By the way, both [freezedry](https://github.com/WebMemex/webmemex-extension/tree/freezedry) and [pdf](https://github.com/WebMemex/webmemex-extension/tree/pdf) branches will extend the page-analysis. I will merge them asap.


>>     It could indeed accept a page (or pageId) instead of a url. I am however
>>     not sure if the imported page should be updated.. Working on
>>     deduplication, I came to think it is cleaner to create a new page object
>>     instead, as you will download the current version from the URL, not the
>>     one that was originally visited and that the page from the history
>>     represents
> Saying this, what is the intention for the existing page doc if the fetchAndAnalyse function should create a new page doc?

As indicated in the [discussion](https://github.com/WebMemex/webmemex-extension/issues/29#issuecomment-296225864) about importing bookmarks, the page stubs represent the supposedly (perhaps formerly) existing page with a known title at a known date and URL. My earlier idea was indeed to fill in the other details of this page when fetching it, but the URL may give us a quite different page than the one that was originally bookmarked/visited. Which title to remember then? To not make false assumptions and end up with a corrupt history of the web, it seems much cleaner to in principle create a new page for the fetched one. If desired, a deduplication strategy can then be used to unify these two pages (e.g. one could decide that they are the same if the title did not change).

**Comment by blackforestboi** [comment]
> Background fetching would be nice though, if it is not too much effort.

Yeah, from a user POV i also don't really consider it to be an option to open each page in a new tab, just to use the same pipeline. 
This also would most definitely lead to performance problems, because each page has to be rendered and we only could fetch one page at a time. 
There are other processes where background fetching is important, i.e. getting urls from external sources that need to be fetched again. 

> but the URL may give us a quite different page than the one that was originally bookmarked/visited. 

Which page version is then indexed for search? Is in your model considered having a latest version that is searched or are all versions of a page searched?
I could imagine that there will be a lot of unnecessary duplicates for a page, without having a proper analysis in place that removes the clutter/detects the differences? i.e. through content on the page that is dynamic? Consider also the use case that a user refreshes the same page a couple of times in the same time span, what happens then, are then just 10(?) page objects created and added to the index? (under the circumstance we cannot properly identify them as duplicates) 
As I understood from @bwbroersma, for search it might be useful to just store a diff of each visit to the original one and make the diff as well searchable. This way we dont lose any content to search.

From my understanding the full-versioning (new page object for each visit) is only necessary for the archiving part, not for search. (Correct me if I am wrong)

> My earlier idea was indeed to fill in the other details of this page when fetching it, but the URL may give us a quite different page than the one that was originally bookmarked/visited.

Idea: In the import process, we could just *not* create a page objects, but just visit and bookmark objects and then when fetching each page create the page object. This way we would not create an unnecessary shell.

**Comment by Treora** [comment]
> Yeah, from a user POV i also don't really consider it to be an option to open each page in a new tab, just to use the same pipeline. This also would most definitely lead to performance problems, because each page has to be rendered and we only could fetch one page at a time.

I don't share this view, but I am happy to go for the background-based approach if you are up for collaborating on that.

> There are other processes where background fetching is important, i.e. getting urls from external sources that need to be fetched again.

Background fetching is indeed better for use cases where disturbing the user would be undesirable (perhaps an automatic link-crawling option), that's my main reason to prefer it.

As for the duplication and search questions, perhaps read e.g. the discussion in #22 again, I think we already discussed most of these questions.

> From my understanding the full-versioning (new page object for each visit) is only necessary for the archiving part, not for search. (Correct me if I am wrong)

Depends on your concept of search; what you want to search. If you just want to keep and search the latest text from each URL, of course you can do things differently. That's not the thing we are making here however, so we approach it more generically, while you can still get the one-version-per-url behaviour through deduplication if you want just that.


> Idea: In the import process, we could just not create a page objects, but just visit and bookmark objects and then when fetching each page create the page object. This way we would not create an unnecessary shell.

Exactly what I described [in #29](https://github.com/WebMemex/webmemex-extension/issues/29#issuecomment-296225864) as a possible but in my current view less desirable alternative.

**Comment by poltak** [comment]
@Treora I've done a bit of work on the WorldBrain repo regarding the fetchAndAnalyse function part of this issue. I tried to describe the changes in [PR](https://github.com/WorldBrain/WebMemex/pull/15). 

Basically it allows the fetching and analyse logic to run in the background by writing fetching logic that, given a URL, will attempt to load the DOM via XHR. Using that, the existing `extract-page-content` logic can be used to grab the same page data without the use of browser tab. Works nicely playing with it manually, and no reason calls to it can't be queued up and handled somewhere (one step at a time though...). 

If you have time, let me know if I've totally misunderstood this issue or I'm heading in the right direction with this.

**Comment by poltak** [comment]
I have a little batch function working on my corresponding PR on WorldBrain fork. It takes advantage of RxJS Observable operators to batch up promises and run them concurrently (without running all at once). I got the idea after learning to play with RxJS, so not entirely sure it's on the correct track, but it works for all my tests so far. Feed in a Set of URL strings and it does the rest. 

If anyone here is familiar with RxJS, would you mind having a look and offering any feedback/opinions? (more info [in this comment](https://github.com/WorldBrain/WebMemex/pull/15#issuecomment-298224482))

**Comment by Treora** [comment]
@poltak: looks nice on a quick look; I will try have a better look tomorrow my morning your evening.

The Rx approach may be a bit complicated, though Rx could be helpful for such tasks; the batching logic could anyway be considered a separate task from the fetch&analyse code, perhaps it is easier to discuss in a separate PR? (feel free to make these PRs upstream if you like)

**Comment by poltak** [comment]
@Treora: Thanks, appreciated. Yes, agreed it should be a separate PR (will sort out today). The two tasks themselves (the batching logic + fetch&analyse logic) are very separate. The fetch&analyse logic works by itself and was written without the batching stuff as a concern. The batching logic is the stuff that implemented as an RxJS observable stream/whatever, and batches fetch&analyse promises (although, it could be written to batch any promise I suppose).

Almost forgot: There's a version of the batching logic on codepen, which uses a fake fetch&analyse logic (just pretends to fetch&analyse a url by waiting 1-5000ms). It has debugging output so you can see what it's doing by looking at the console. https://codepen.io/poltak/pen/XRRdeR?editors=0011

**Comment by Treora** [comment]
Closing this issue; features like this one have been fading off the roadmap for a while. Maybe some day..
