### ISSUE TITLE
Deprecated packages warning when doing `npm install`

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#31]
It all works, but when doing `$ npm install` it is mentioning: 
Might not be a problem...dunno :)

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated husl@5.0.3: Project renamed to HSLuv

**Comment by Treora** [comment]
Thanks for noticing, but all of these are dependencies of dependencies (of dependencies...), so they will have to be dealt with in those projects. NPM is often a bit noisy, we could add a `--loglevel=error` but that may suppress useful warnings too.
