### ISSUE TITLE
Quick Blacklist & Forget

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#36]
Quickly blacklist a domain from the drop down menu: 
<img width="230" alt="screen shot 2017-03-01 at 19 14 29" src="https://cloud.githubusercontent.com/assets/7870039/23474223/50b440de-feb3-11e6-8ad4-9dc5429230b7.png">

Steps: 
- Click List Element "Put domain on Ignore List"
- Prompt pops up: "Do you want to delete every page that you already visited under this domain from the database?"
- If yes, delete all the data related to the domain from the database & **put domain on blacklist**
- If no, just put domain on blacklist

**Comment by Rohanhacker** [comment]
Is there anyone working on this?

**Comment by Treora** [comment]
I forgot this issue was still around; it overlaps completely with #21, so I'm closing it.
A first start on forgetting a page was made in #67. Before the aspect of blacklisting can be added #20 should be finished.

**Comment by blackforestboi** [comment]
I don't think they are one and the same. Here its more about the UI for the Quick Blacklist. But indeed the other features need to be finished first. 

May have to be reopened later again.
