### ISSUE TITLE
Pause recording of history/activity

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#38]
A user should be able to pause the recording of their history and activity, for periods of time. 

Proposed Workflow: 
1) Open Dropdown:
<img width="230" alt="screen shot 2017-03-01 at 19 14 29" src="https://cloud.githubusercontent.com/assets/7870039/23474889/a932fb40-feb5-11e6-8c7c-c3e24319bd9b.png">

2) Select "Pause WebMemex"
3) Select time frame in hours
4) confirm

Now everytime the user opens the popup, there should be the ability to stop the pause. Maybe just show a timer than runs down with a small X Button on the side.
Example:
`Pause for: 3:45h    x`

**Comment by Treora** [comment]
Do you mean you would like to pause the logging of your browsing? I think that could be useful. Browsers do have incognito window/tabs that have a very similar purpose, and that are more thorough as it also prevents the visits from being added to the browser's history log. It could be that something less thorough is sometimes desired though, as incognito mode completely disables the extension.

**Comment by blackforestboi** [comment]
@Treora Good point, might be something that we can postpone for later.
The only use case I see it as useful to pause is that the extension is still usable while doing incognito research.

**Comment by Treora** [comment]
Ok, closing this for now then.
