### ISSUE TITLE
Filter by bookmarks

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#39]
## User story

As a user, I want to filter my results by bookmarks.

**Comment by Treora** [comment]
Good idea. UI-wise, perhaps we could add a small button to the search query to open up some search choices, including a toggle for this (and soon a time filter and probably other things).

**Comment by wimpykid26** [comment]
@Treora @oliversauter in reference to https://github.com/WebMemex/webmemex-extension/issues/29

How do we differentiate if the entry in the model is a bookmark. Is only the nonce used to differentiate between a bookmark and other entries?.

**Comment by blackforestboi** [comment]
@wimpykid26 We'll discuss about it today.

**Comment by Rohanhacker** [comment]
can I work on this ?

**Comment by blackforestboi** [comment]
For now, we have not represented a bookmark as such in the data model, therefore a complete implementation is blocked.

@Treora An important question still to answer: Should we treat a bookmark as a separate object type, as for example visits or for now just as a flag inside the page object (`is_bookmark`)?

**Comment by Treora** [comment]
> @Treora <https://github.com/Treora> An important question still to
> answer: Should we treat a bookmark as a separate object type, as for
> example visits or for now, just as a flag inside the page object
> (|is_bookmark|)?
>
Separate object type.

**Comment by Treora** [comment]
Closing this issue; the assumption here was that the results would also contain many pages that were automatically stored, which is now off the roadmap. Some form of integration with bookmarks may still be interesting but would have to be reimagined.
