### ISSUE TITLE
Overhaul overview (search results)

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#40]
The current search results are somewhat limited in the amount of info to be able to see/skim. The space could be used more efficiently. 

## The issues I see:
1. Space not used, so no place to show additional important info for the search results:
![screen shot 2017-03-01 at 21 57 32](https://cloud.githubusercontent.com/assets/7870039/23480988/31ce56c0-feca-11e6-8ee3-4c2fe4efebbd.png)

2. The title-background is basically covering half of the screenshot, making it only half as useful. (no pun intended) :)
<img width="260" alt="screen shot 2017-03-01 at 21 56 57" src="https://cloud.githubusercontent.com/assets/7870039/23480946/06c23668-feca-11e6-847e-19d1d9757c80.png">

3. Only info shown is a icon for the page (which is not always there) and a very short excerpt of the title + half the screenshot.

4. The groupings group pages from similar domains, I dont see that as very useful, especially in the search results, because I have to do one more step in order to find out which one is mine. If I am browing on the same page a lot (GitHub could be one) I have to hover over each element in order to find out which one was the correct.

5. The elements indicating the pages visited before and after a search result take too much space and are not really clear to which they belongs, or if it is a continuation. (Ultimately its not clear to the user what they are at all)

## What I propose:
A combination of what is currently in place and what @aquibm developed a few weeks back (with screengrab-gif): https://github.com/WorldBrain/Research-Engine/pull/91

So the combination would be to have the screenshot on the left, with title and excerpts of the results page on the right, making the results about 2,5/3 times as wide as they are now. 

I would throw into the room of removing the groupings with the layers behind each other. And just let it be a list of elements in the search results. 

And lastly making the before and after pages simply a list of titles that maybe expand to the whole element by hovering over them. Also adding some indication that its what came before and after. 

@Treora @aquibm @obsidianart 

What do you guys think?

**Comment by Treora** [comment]
The current design is just what I quickly developed to get something usable, but I would be happy if somebody created something nicer. There is a reason for the empty space and small size of the items: the intention is to create a two-dimensional graph layout rather than a single column as it is now. As this may not materialise soon, it would probably be good to make some quick improvements on the current single-column design.

Clustering pages needs to be reconsidered or redesigned, the way it is done now is impractical indeed. Likewise for showing context around search results. These aspects are currently really just a quick hacks I added to provide a glimpse of the direction in which the interface should be heading, and will only really become useful when we have better ways to determine what is relevant context and what are sensible clusters, and when we have a better, two-dimensional visualisation.

**Comment by blackforestboi** [comment]
What do you think about a next step of just having a simple search results list with the elements, and as an additional task adding the features of before/after history (context) and some sort of grouping afterwards again? This way we would have a start and a very small, doable task also newcomers could take on?

**Comment by Treora** [comment]
While rewriting the overview it would indeed be easier to skip the context and clustering stuff at first. It would be nice to have a design plan to work towards which does already draw out how to add these features and other interactivity (e.g. note taking). Creating this may not be so suitable as a newcomer task, and something that I should probably put some effort into myself, as many ideas are still locked up in my head and notebooks.

But for now, it would be a fine and not too large task for anyone to just redesign the items to show more information, which is if I understand you correctly the main thing you are looking for.

**Comment by blackforestboi** [comment]
> which is if I understand you correctly the main thing you are looking for.

Yes. just to make sure that is transported. I like the idea of the context a lot :) would just be good to make the first step of having skimmable and informative results. 
And it could be a doable first small task to transfer these. 

@Treora @aquibm, can we use what Aquib has done as a base?(https://github.com/WorldBrain/Research-Engine/pull/91)

Regarding the design plan, good idea, It became increasingly clear through the calls that a wiki is needed to communicate and discuss all the different concepts. i.e. the subprojects, stuff like in which format data is stored, designs etc. 
So i will use the time after the calls to set one up where we can document things like that.

**Comment by reficul31** [comment]
I would like to take up this issue. According to me the steps to follow are:
* Refactor the design and get it approved.
* Clean up the component
* Add the design all the while avoiding to mutate the component as much as possible.

Added feature:
* We can have like a focus div on the screenshot as soon as the mouse focuses on the tab.

If this is approved I will post the initial design for input.

**Comment by reficul31** [comment]
![webmemex_mock](https://cloud.githubusercontent.com/assets/19486491/23558595/3a34d1cc-005a-11e7-8cfb-6f8bf555fc7a.jpg)

I tried to follow as closely I could the design given by [pr](https://github.com/WebMemex/webmemex-extension/pull/30) Obviously the fonts will be changed to whatever was being used. Feedback needed so that I can start updating the components.

I also want to implement onfocus zoom feature on the screenshot.

**Comment by blackforestboi** [comment]
Hello @reficul31 great! 

I like the simplicity of it. (as I did when @aquibm built it in the first place ;)
Props for onzoom on the screenshot! I like the idea. 

The only thing I would differently for now is to have the screenshots without the white border, but directly fitting into the top right corner + with the same width.

If I am not mistaken, the search overview is a separate react application and not inside the overview, as build by @aquibm in: https://github.com/WebMemex/webmemex-extension/pull/30

**Comment by reficul31** [comment]
![webmemex_mock1](https://cloud.githubusercontent.com/assets/19486491/23562181/6ed4ed7e-0067-11e7-8fa4-876d24dca56e.jpg)

@oliversauter thanks for the input will put up the updated design asap. I know the overview is a different component from the settings component but I had no idea how the theme will be around the component so just to fill the page I added it(if that makes any sense). 
I have removed the settings theme around the overview component. Is this looking better?
ps. Anymore functionality that comes to your mind?

**Comment by blackforestboi** [comment]
looks nice!

yeah, there is something, as discussed with @Treora earlier in the thread (https://github.com/WebMemex/webmemex-extension/issues/40#issuecomment-283665553)
We want to remove the grouping of pages that are from a similar domain. (at least for now)
And another thing, the display of pages that come before and after a search result. (you have to visit a few pages for that and then make a search query to see it)

So basically just make it a simple list.

I would though, leave the small disk icon that lets you access a locally stored version of the page. (great feature)
We could put it in the top-right corner, left of the screenshot. 

This is the icon currently:
<img width="521" alt="screen shot 2017-03-03 at 19 26 16" src="https://cloud.githubusercontent.com/assets/7870039/23563557/7a676eca-0047-11e7-987f-57f46d72bd4c.png">

I would chose an icon that fits more into the theme though.

**Comment by Treora** [comment]
> We want to remove the grouping of pages that are from a similar domain. (at least for now)

For clarity: I would not *want* to remove the clustering (how I call the grouping), but it may be extra effort to adapt the design for it, and needs to be done better anyway, so it is acceptable if it disappears for the moment while redesigning things.

By the way, if you did not do it yet, some changes for the design may also have to be done in the [ResultList code](https://github.com/WebMemex/webmemex-extension/blob/83f39b260a8d331baeb7ede5d89c0f1c80dbb267/src/overview/components/ResultList.jsx), which sets the vertical distance between items and adds a time stamp in between if there is a big gap.

I would be happy to see something more modern than the floppy disk :floppy_disk: (it's so old it has become cute though), but I found it hard to come up with something as widely understood to represent a saved document.

**Comment by blackforestboi** [comment]
> For clarity: I would not want to remove the clustering (how I call the grouping), but it may be extra effort to adapt the design for it, and needs to be done better anyway, so it is acceptable if it disappears for the moment while redesigning things.

It shouldnt sound like it should be removed completely, my bad. In my understanding it would have been temporarily so that we first have a clean simple list and then find a solution to the clustering in a next step ("While rewriting the overview it would indeed be easier to skip the context and clustering stuff at first.")

>(it's so old it has become cute though)

Thought about just having something more modern in terms of style, the icon is quite fitting: Maybe the first one in this list: https://icons8.com/web-app/for/all/floppy

**Comment by Treora** [comment]
> Thought about just having something more modern in terms of style, the icon is quite fitting: Maybe the first one in this list: https://icons8.com/web-app/for/all/floppy

Ah ok, good point. I just used the unicode character for a floppy (yes that exists), but it would be good to put an image there. The icons8 you suggest is not so nice copyright-wise though:
> Don’t forget to include a link on each page that you use our icons.

I love pixabay for only having CC0 (public domain) images, [here](https://pixabay.com/en/photos/?min_height=&image_type=vector&cat=&q=floppy+disk&min_width=&order=popular) are some vector drawings of floppies. Heh, we could take (possibly retouch) [this](https://pixabay.com/en/floppy-disk-diskette-media-memory-27785/) even older floppy type to obtain some extra style points. :)

**Comment by blackforestboi** [comment]
>The icons8 you suggest is not so nice copyright-wise though:

Also good point. 

> Heh, we could take (possibly retouch) this even older floppy type to obtain some extra style points. 

Making it really a "historical element"  :)

I favorite [one without color]( https://pixabay.com/en/floppy-disk-diskette-data-old-24172/), would fit better into the clean style. 

A perfect combination would be your suggestion just in black and white :)

**Comment by reficul31** [comment]
@oliversauter I didnt want to overlay anything on the screenshot so I added the save icon before the screenshot. According to me this design looks a bit cleaner than overlaying the icon on the screenshot.
@Treora I guess this is what you needed with the time stamp coming when the gap is too much?
The fonts will be changed. Also I am a bit confused should the code for grouping be there or not?
PS. Any other cool features come to your mind?? 
![webmemex_mock2](https://cloud.githubusercontent.com/assets/19486491/23574840/804c7648-00a9-11e7-8b87-1114f5380655.jpg)

edit: After designing most of the component I have come to realize that there will be some links in which the favicon is not present. For those links how about we put the icon of webmemex?

**Comment by RohanMishra97** [comment]
This seems nice!
I'd like to make a suggestion if I may, the user should have an option to delete any webpage from his overview and on adding it to the UI now, we can later add code to make it functional.
Cheers!

**Comment by blackforestboi** [comment]
@reficul31 
I think there was a misunderstanding, my idea was also to put it where you just put it, not over the screenshot itself. So well handled, thanks :)

As I understood it regarding the code for the grouping, it would disabled for now until we found a better way to represent it in the UI. Doing that could be a good next task to take on then. 

@RohanMishra97 
Thanks for the great input, we thought about this already before. Great that you reminded us about that here. I just see that that there is not yet an issue for that.

As for your both inputs I made a quick mockup:

<img width="986" alt="screen shot 2017-03-04 at 10 14 21" src="https://cloud.githubusercontent.com/assets/7870039/23577612/6e917e10-00c4-11e7-8799-57c809e588a9.png">

**Comment by Treora** [comment]
@reficul31:
> @Treora I guess this is what you needed with the time stamp coming when the gap is too much?

I meant that `— 8:40 —` between the items indeed. I did not mean that it is *needed*; just saying that it is there now, but a new design could choose to do it differently.

**Comment by reficul31** [comment]
@oliversauter @Treora:
>edit: After designing most of the component I have come to realize that there will be some links in which the favicon is not present. For those links how about we put the icon of webmemex?  

Should I act upon this or not. Also the groupings, just to confirm one last time, are supposed to be removed? Also is the PR to be sent to master or to some other branch?

edit:
The screenshot of how the component looks on my machine as of now
![screenshot from 2017-03-04 17 39 40](https://cloud.githubusercontent.com/assets/19486491/23578639/e1055e34-0101-11e7-8e30-4010efb14678.png)

**Comment by blackforestboi** [comment]
> edit: After designing most of the component I have come to realize that there will be some links in which the favicon is not present. For those links how about we put the icon of webmemex?

Sorry for not answering. IMO we could just make a "blank page icon" so the standard one, not using a WebMemex icon, makes it clearer that there is no favicon. 

Regarding the groupings we would just need Gerbens confirmation and we can go for removing the groupings (for now)

**Comment by Treora** [comment]
As said, feel free to remove the clustering for now. We will draft a new design which approaches it more thoroughly.

Putting a WebMemex logo on other websites seems a wrong kind of self-advertisement indeed (also, we still need a proper logo).

**Comment by blackforestboi** [comment]
@reficul31 
thanks for your quick feedback-loop cycle! 
I just see that it would make sense to put a vertical line on the left side of the screenshot, so there is a clear separation. This seems needed for the case that there is no screenshot yet. 
Because in that case the icons look somehow misplaced. 

Is there a reason you chose to make the icons horizontal, not vertical? Not that I have a strong preference, just understanding your reasoning. 

Also we could think of having a text shown centered horizontally and vertically where the screenshot is, in case there is none: "No screenshot available"

**Comment by reficul31** [comment]
Duly noted @oliversauter 
Will implement the changes and upload the screenshot again.
>Is there a reason you chose to make the icons horizontal, not vertical?  

No reason, I guess I didn't put much thought into it. Now on second take I guess I should make them vertical only.
@Treora I guess I will keep the clustering on for now as I don't feel too comfortable removing such a big feature.

**Comment by reficul31** [comment]
Sorry for the delay I have implemented all the changes and the final screenshot looks something like this.
![screenshot from 2017-03-05 08 29 56](https://cloud.githubusercontent.com/assets/19486491/23584147/25b62a50-017e-11e7-9260-9d84cca5057e.png)

Please tell me if other changes are required I will be happy to implement them. Please confirm the design once so that I can send the PR. Thanks.

>Also is the PR to be sent to master or to some other branch?

**Comment by blackforestboi** [comment]
Hello @reficul31 

Thanks a lot :)

> Please tell me if other changes are required I will be happy to implement them. Please confirm the design once so that I can send the PR. Thanks.

I would add a small space between the icons and the screenshot. 
Also, if you don't have any strong objections, I would add a vertical line on the left border of the screenshot, so in case no screenshot is there, that the icons don't look like hanging in the air.

Finally, I think we should remove the background image, it doesnt really fit well IMO to the style of the rest.

**Comment by reficul31** [comment]
@oliversauter Thanks for the input. Here are all the changes implemented.
![screenshot from 2017-03-05 20 16 29](https://cloud.githubusercontent.com/assets/19486491/23588258/d3879c6a-01e0-11e7-8978-1e0709a3e748.png)

Although in my opinion I think we shouldn't remove the background as the plugin followed a theme which the background complemented. Unless we come up with a concrete design to implement ,changing the theme defining components should be avoided.
@Treora any inputs or changes required?

**Comment by blackforestboi** [comment]
I like it more with the white background, but have no hard feelings about it.

**Comment by reficul31** [comment]
Shall I make a PR then?
>Also is the PR to be sent to master or to some other branch?

**Comment by blackforestboi** [comment]
Jup :) Go ahead! Thanks a lot. 

> Also is the PR to be sent to master or to some other branch?

All the recent PRs were made directly to master, so you can put it there as well.

**Comment by Treora** [comment]
I lost track of whose commits went where, but I continued building from @reficul31's branch (#55), cleaned up the code structure, fixed some layout issues (e.g. on smaller window sizes), and tweaked the design some more:

![screenshot](https://cloud.githubusercontent.com/assets/4191409/24753093/04d19358-1ad1-11e7-9754-46b92013f093.png)

I ended up having not both a big fav-icon and a big screenshot, but only the screenshot, while showing the icon instead if no screenshot is available (also the icon is always shown small besides the title). I also enlarged the screenshot, as to me it feels like the core thing, not just a preview that is nice to have.

@oliversauter: I imagine you may have different preferences. If so, for use in WorldBrain you might want to use this version but revert just [the commit](1f01996) that moves around most of the design. This would give you the layout&code cleanup, but still have the design mostly as Shivang and you made it.

As I have said [above](https://github.com/WebMemex/webmemex-extension/issues/40#issuecomment-283644256), I would really like to move to a more graph-like view in the longer term. This overhaul however seems like an improvement we can use until such a new visualisation comes about. Merging this design, closing this issue, and moving on.
