### ISSUE TITLE
Testing the tool

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#42]
So that @rusuo can get started with exploring the tool with the eyes of testing it, we may compile a list of functions we deem to be most important to cover.

Just as a disclaimer: I am unexperienced in defining test cases, what I aim to do here is just listing the basic high level processes that should not fail and I aimed to spark a discussion with all those. We may also open up a project for all the test tasks. The ones with 'X' in the end are not yet developed
This list is unprioritised: 

- Storing a visited page as a new entry
   - Title
   - text
   - screenshot, if available
- Searching and displaying results
- New entry added to index
- Importing all history items from history API and storing them as new entries (without text content)
- Importing all bookmark items from history API and storing them as new entries (without text content) 'X'
- Batch fetch all URLs without downloaded text content'X'
- Downloading HTML of those URLs 'X'
- Cleaning HTML to get text 
- Storing HTML to existing page object 
- Storing extracted Text to existing page object 'X'
- On new visit to existing page, add visit Object to it. 

@Treora Do you have some in mind you would like to add?

**Comment by Treora** [comment]
As discussed out of band, this discussion is to be continued elsewhere.
