### ISSUE TITLE
Delete a single page from the DB

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#48]
As a user I should be able to delete a single page from the DB.

Ideally this happens in the search results list, as @RohanMishra97 reminded us in this thread:
https://github.com/WebMemex/webmemex-extension/issues/40#issuecomment-284130469

I assume that @reficul31 will implement it in the UI, so we need someone who implements the deletion from the DB.

Although here might come the question, if we now automatically delete the page object and all the visit objects as well, or just a single visit? 
I would go for the first one. 

##### Mockup
<img width="986" alt="screen shot 2017-03-04 at 10 14 21" src="https://cloud.githubusercontent.com/assets/7870039/23577665/4d540c4e-00c5-11e7-9266-7a9e55ac5456.png">

**Comment by Treora** [comment]
This is exactly what is being discussed in #21, let's keep the discussion in one place.
