### ISSUE TITLE
Searching for 'search1' creates a card with http://search1.com - cannot reproduce every time

### ISSUE THREAD

**Issue by rusuo** [WebMemex/webmemex-extension#51]
(I cannot reproduce it every time)

1. Open a new tab
2. In the search bar, enter 'search1' text
3. Go to the extension

Actual results:
An entry with "http://search1.com" is created

Expected results:
An entry with "search1" under Google is created

**Comment by Treora** [comment]
Interesting. I imagine your browser (which?) tries to load both the page 'search1.com' and search results when you type 'search1', and depending on the speed of their responses either the one or the other may be logged.. Not sure how exactly, but we may need some pragmatic workarounds for things like this. Filtering out visits shorter than a few seconds may be helpful anyway to remove such clutter, as well as some redirection pages.

**Comment by rusuo** [comment]
I was using Chrome. Being related to the speed the page loads make sense, considering the fact that I cannot reproduce it every time

**Comment by Treora** [comment]
Closing this issue; automatically logging visited pages is off the roadmap now, so this problem no longer exists.
