### ISSUE TITLE
When clicking on an entry, open a new tab, instead of the same one

### ISSUE THREAD

**Issue by rusuo** [WebMemex/webmemex-extension#52]
When clicking on an entry from your history, currently it is opened in the same tab.

I would suggest to be opened in a new tab, for having an easier to come back to the history, or to check what is happening

**Comment by blackforestboi** [comment]
Good idea! 

Actually right now I can't open the results in a new tab with cmd+click. I have to deliberately right click and then on "open in new tab", which is quite cumbersome, especially when you want to open more than one result.

**Comment by Treora** [comment]
I personally dislike making the same-or-new-tab choice for people, and every history view or search results page I know does not open results in a new tab by default. The items are just links, so Ctrl or middle-mouse click should just open them in a new tab as usual. I wonder why it does not work for you with cmd+click.

More generally, I am still thinking how and when to present the overview anyway. In every new tab is a choice that may be reconsidered, and also only works in Chrome|ium. Seeing your history when closing a tab may be useful, or having it as a permanent special tab (like a 'pinned' tab). Decisions on this can be made and changed later, user research is welcome.

**Comment by anona-R** [comment]
I will open a PR soon on this 👍

**Comment by blackforestboi** [comment]
@Treora 

I just tested it also on Firefox and have the same issues. Might be ok to make the choice for now and let people make a decision later on.
With the PR @uchithaR just made it also not working, so it does not really solve the issue of being able to open multiple ones quickly. 

MIght not be the most common use case after all. Still, i would leave the open-in-new tab for the reason that if people make a search, they would have to go back and retype everytime they visited the wrong page and redo the search.

**Comment by Treora** [comment]
@oliversauter: Hah, I know what causes the issue for you: Cmd key is mapped to the Meta key, which I [used for debugging](https://github.com/WebMemex/webmemex-extension/blob/4ab650850cecdc66b94eb64cb21da798815cef48/src/overview/components/VisitAsListItem.js#L20). Will change this.

**Comment by Treora** [comment]
Doing the debugging on ctrl+meta now, as it seemed quite a handy feature to keep. I hope that is not needed for something..? (opening in a new window is cmd+shift on Mac, I suppose?)

**Comment by blackforestboi** [comment]
Sometimes its the simple things :)

> I hope that is not needed for something..?

on mac it does a right click and opens the context menu. Seems less problematic, didn't even know I can open the right click menu like that.  :)

**Comment by obsidianart** [comment]
on mac is cmd+click for chorme

**Comment by blackforestboi** [comment]
> on mac is cmd+click for chorme

You mean it's only a command in chrome?

**Comment by Treora** [comment]
Assuming the Cmd+click works again now, I am closing this one, as I still think the choice should be up to the user. Having a link that always opens in a new window reminds me of those websites that want to keep you on their site, and feels like a bad practice.

> Still, i would leave the open-in-new tab for the reason that if people make a search, they would have to go back and retype everytime they visited the wrong page and redo the search.

As for this, for now one can just open results in a new tab by ctrl/cmd/middle-click. At some moment we can also make the search query part of the url or history state, so going back would work as expected (it should also be much quicker to be usable though).
