### ISSUE TITLE
Show a message for "no results found"

### ISSUE THREAD

**Issue by rusuo** [WebMemex/webmemex-extension#53]
When searching does not return any result, show a message to inform the user that no results were found

**Comment by Chaitya62** [comment]
Submitting a PR soon

**Comment by blackforestboi** [comment]
What is the progress of this? @Chaitya62

**Comment by rachanamamillapalli** [comment]
Can I work on this task? - newcomer

**Comment by oliversauter** [comment]
@rachanamamillapalli already in the making, as the label suggests :)
 
Here is the corresponding PR: https://github.com/WebMemex/webmemex-extension/pull/56

**Comment by Chaitya62** [comment]
@oliversauter. PR review is left

**Comment by davidemdot** [comment]
Hi, @oliversauter,

Last message means this issue is free now?

**Comment by Chaitya62** [comment]
@davidemdot no I am working on it

**Comment by davidemdot** [comment]
Sorry, @Chaitya62, I misunderstood you.
