### ISSUE TITLE
Package as Chromium extension

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#9]

**Comment by davidemdot** [comment]
There is a bash script in the Chrome documentation for automating the packaging of a Chrome/Chromium extension.

You can have a look here:

https://developer.chrome.com/extensions/crx#scripts

**Comment by Treora** [comment]
Ah nice, thanks @davidemdot. I tried using Chromium itself for packaging, either through the GUI (in chrome://extensions), or command line:
`chromium-browser --pack-extension=./extension --pack-extension-key=../extension.pem`

Whichever way works seems fine to me.

**Comment by Treora** [comment]
I added a few lines to the gulp file (in 968bba4) to call `crx`. Easy peasy.
